import localFont from "next/font/local";
import { NextUIProvider } from "@nextui-org/react";
import Navbar from "@/src/components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/src/components/Main/Footer/Footer";


export const metadata = {
  title: "Ava Sanat",
  description: "Generated by create next app",
};



const vazir_light = localFont({
  src: [
    {
      path: "../../public/fonts/Vazirmatn-Light.woff2",
    },
  ],
  variable: "--font_1",
});
const vazir_medium = localFont({
  src: [
    {
      path: "../../public/fonts/Vazirmatn-Medium.woff2",
    },
  ],
  variable: "--font_2",
});
const vazir_demiBold = localFont({
  src: [
    {
      path: "../../public/fonts/Vazirmatn-SemiBold.woff2",
    },
  ],
  variable: "--font_3",
});
const vazir_bold = localFont({
  src: [
    {
      path: "../../public/fonts/Vazirmatn-Bold.woff2",
    },
  ],
  variable: "--font_4",
});



export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className={`${vazir_light.variable}  ${vazir_bold.variable}  ${vazir_demiBold.variable}  ${vazir_medium.variable} rtl`}>
        <NextUIProvider>
          <Navbar/>
            {children}
            <Footer/>
        </NextUIProvider>
      </body>
    </html>
  );
}
