import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ava Sanat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className={`${inter.className} rtl`}>
        <NextUIProvider>
          <Navbar/>
            {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
